### ISSUE TITLE
Update Mapbox key

### ISSUE THREAD

**Issue by hanbyul-here** [NASA-IMPACT/delta-config#10]
- It probably is a good idea to generate a new key dedicated to delta dashboard, url protected to staging/production url. (I meant to just swap the key but it seems the mapbox style is attached to the current key. I was not sure if there is anything special about this style so I left it as it is.)

**Comment by aboydnw** [comment]
@hanbyul-here I believe this is complete, yes?

**Comment by hanbyul-here** [comment]
Yes!
